#server
server:
  port: 80
  servlet: 
    context-path: /
  tomcat:
    max-threads: 1000
#mybatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    default-statement-timeout: 30
  mapper-locations:
  - classpath:/mapper/*/*.xml
#spring
spring:
  datasource:
    url: jdbc:mysql:///restaurant?serverTimezone=GMT%2B8
    password: root
    username: root
  thymeleaf:
    prefix: classpath:/templates/pages/
    suffix: .html
    
#log
logging:
  level:
    com.cy: DEBUG